const path = require('path');
const SERVER_ROOT = path.resolve(__dirname, '..');

module.exports = {
  JWT_SECRET: process.env.JWT_SECRET,
  ACCESS_TOKEN_TIME: 60 * 60,
  SALT_ROUNDS: 5,
  SQUADHELP_BANK_NUMBER: '4564654564564564',
  SQUADHELP_BANK_NAME: 'SquadHelp',
  SQUADHELP_BANK_CVC: '453',
  SQUADHELP_BANK_EXPIRY: '11/26',
  CUSTOMER: 'customer',
  CREATOR: 'creator',
  CREATOR_ENTRIES: 'creator_entries',
  CONTEST_STATUS_ACTIVE: 'active',
  CONTEST_STATUS_FINISHED: 'finished',
  CONTEST_STATUS_PENDING: 'pending',
  CONTESTS_DEFAULT_DIR: 'public/contestFiles/',
  NAME_CONTEST: 'name',
  LOGO_CONTEST: 'logo',
  TAGLINE_CONTEST: 'tagline',
  OFFER_STATUS_PENDING: 'pending',
  OFFER_STATUS_REJECTED: 'rejected',
  OFFER_STATUS_WON: 'won',
  FILES_PATH: 'public/',
  SOCKET_CONNECTION: 'connection',
  SOCKET_SUBSCRIBE: 'subscribe',
  SOCKET_UNSUBSCRIBE: 'unsubscribe',
  NOTIFICATION_ENTRY_CREATED: 'onEntryCreated',
  NOTIFICATION_CHANGE_MARK: 'changeMark',
  NOTIFICATION_CHANGE_OFFER_STATUS: 'changeOfferStatus',
  NEW_MESSAGE: 'newMessage',
  CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',
  LOG_FILE: path.resolve(SERVER_ROOT, 'src/logger/log.ndjson'),
  LOGS_DIR: path.resolve(SERVER_ROOT, 'src/logger/logs'),
  LOG_ENCODING: 'utf8',
  LOG_ARCHIVE_SUFFIX: '-backup.ndjson',
  TIMEZONE: 'Europe/Kyiv',
  USER_PREVIEW_ATTRIBUTES: [
    'id',
    'firstName',
    'lastName',
    'displayName',
    'avatar',
  ],
};
